### ISSUE TITLE
[Bug]:  failure in 9.99 with "'FOOTPRINT' object has no attribute 'HasProperty'

### ISSUE THREAD

**Issue by danielchisholm** [bennymeg/Fabrication-Toolkit#205]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/bennymeg/Fabrication-Toolkit/issues) for a bug report that matches the one I want to file, without success.

### Fabrication Toolkit Version

5.0.1

### KiCad Version

9.99

### What operating system are you using?

Other Linux

### What arch are you using?

None

### Expected Behavior

"that it works" (sorry)

### Actual Behavior

When the "Generate" button is pushed an error window popup appears '**FOOTPRINT' object has no attribute 'HasProperty'** and nothing is exported/created.

### Additional Information

After working with 9.99 for a while, following a recent updated to kicad-nightly (9.99) the tool is now broken.  It still works for me with 9.0.

This look to be the same as issue #124, which happened shortly after 7.99 became 8.0.

I am half-suspecting a regression on the KiCAD side of things and am happy to file a bug report there (but to get it considered seriously it would help to know that the problem seems not obviously be the fault of the plugin.

The same behaviour occurs with the plugin "com.github.pcbway.PCBWay-Plug-in-for-Kicad", however "https://github.com/bouni/kicad-jlcpcb-tools" works properly (perhaps it interfaces in a different manner).

**Comment by bennymeg** [comment]
> I have searched the [issue tracker](https://www.github.com/bennymeg/Fabrication-Toolkit/issues) for a bug report that matches the one I want to file, without success.

Please actually search next time.
